services:
  postgres:
    image: postgres:17
    container_name: postgres17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: public
    ports:
      - "5432:5432"
    volumes:
      - ./server/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  flask_app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: flask_app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: public
      DB_USER: postgres
      DB_PASSWORD: password
      POPULATE_DB: "true"
    ports:
      - "5050:5050"
    volumes:
      - ./server:/app
    depends_on:
      postgres:
        condition: service_healthy

  nextjs_app:
    build:
      context: ./interface
      dockerfile: Dockerfile
    container_name: nextjs_app
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5050
    ports:
      - "3000:3000"
    depends_on:
      - flask_app
